//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 a,a:active,a:hover,a:visited{color:inherit;text-decoration:none;cursor:default}*{padding:0;margin:0;-webkit-user-drag:none;user-select:none} 的本地化字符串。
        /// </summary>
        internal static string style_min {
            get {
                return ResourceManager.GetString("style_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 const native={};window.native=native,(async()=&gt;{function e(e,t){let a=native,n=e.split(&quot;.&quot;);for(let e=0;e&lt;n.length;e++){let i=n[e];e!=n.length-1||a[i]?a[i]||(a[i]={}):a[i]=t,a=a[i]}return n[n.length-1]}let t=0,a={},n=&quot;__&quot;,i=&quot;__oject_describes&quot;,d=[&quot;window&quot;,&quot;window.parent&quot;,&quot;device&quot;];async function o(n){let i={};if(native.__oject_describes[n]=i,!await new Promise((e,d)=&gt;{a[t]={callback:e,target:i},chrome.webview.postMessage({Type:0,Id:t++,Name:n,Args:[]})}))return e(n,new Proxy(i,{get:(e,i,d)=&gt;{if(null==e[&quot;__&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string web_ui_sdk_min {
            get {
                return ResourceManager.GetString("web_ui_sdk_min", resourceCulture);
            }
        }
    }
}
